extends:
  - '@form8ion'
  - '@form8ion/mocha'
  - '@form8ion/cucumber'

overrides:
  - files: example.js
    rules:
      import/no-extraneous-dependencies: off
  - files: templates/*.js
    rules:
      import/no-unresolved: off
      import/extensions: off
